### ISSUE TITLE
Disable v12 Animation

### ISSUE THREAD

**Issue by brunocalado** [muhahahahe/8bit-movement#1] opened 2024-07-23 16:31 UTC
Hi. Can you disable the animation when you change the image?

https://github.com/user-attachments/assets/12f2d934-94fa-40cc-8506-d31ed274be2e

**Comment by brunocalado** [comment] 2024-07-23 18:26
> Cant reproduce, disable all modules besides 8bit-movement and tell me if it still happens

This animation is a foundry thing. I don't have modules.
![image](https://github.com/user-attachments/assets/499a6430-e07b-42f6-abea-5a94825bc013)

**Comment by muhahahahe** [comment] 2024-07-23 18:34
was able to reproduce with setting the max fps all the way down,
sry cant do anything there
![image](https://github.com/user-attachments/assets/c28a59da-6c90-4fa3-904d-f74eb2630995)

**Comment by brunocalado** [comment] 2024-07-23 19:17
> was able to reproduce with setting the max fps all the way down, sry cant do anything there ![image](https://private-user-images.githubusercontent.com/3751847/351448592-c28a59da-6c90-4fa3-904d-f74eb2630995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjI0MzYsIm5iZiI6MTcyMTc2MjEzNiwicGF0aCI6Ii8zNzUxODQ3LzM1MTQ0ODU5Mi1jMjhhNTlkYS02YzkwLTRmYTMtOTA0ZC1mNzRlYjI2MzA5OTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTkxNTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc1MmFlODU5YWIzZDlhNjJkOTVkMDQ3ZWQ0ZDFiNTk0MTNmYTAyNzkwNTYyNTM3NTllOTI1MmFkNzUzMWY4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kLbJ25X9ADG3dE960_YSg6VLCqIwXJyxG1jML0THvJY)

The problem only happens when I add the images. After that if a press f5, it work well.
![image](https://github.com/user-attachments/assets/62dd5ded-787c-44d1-bf05-846756012aee)

**Comment by mocandragon** [comment] 2024-07-27 06:41
Him writing to note I get the exact same issue, even with only this module enabled. Notably, it only happens when rotating on the spot and not when moving. Foundry is also running at 60fps, so that's not the issue.

**Comment by muhahahahe** [comment] 2024-07-27 06:52
Yeah i have had a private chat with them. It seems like this issue is caused by Foundry's initial token image change which has the animation attached to it. I dont think i can do much about it and i left this issue open so people see that this will be fixed after pressing F5 (refreshing).

**Comment by mocandragon** [comment] 2024-07-27 22:04
When do you refresh to fix this? Immediately after creating the token but before adding the direction images? Immediately after adding the images? Do you need to use the automatic naming convention thing, or can you add images through the gui?

**Comment by muhahahahe** [comment] 2024-07-28 13:27
I dont know what to tell you, other than "its weird"!
I made a fix but it requires libwrapper to not cause problems with other modules or to prevent them.
It still might have some undesired behaviors

*It appeared having libwrapper activated in a game world already fixed it partially ( the animation did not took a full second )*

I hope this is now resolved

**Closed** 2024-07-30 12:17 UTC
Labels: fixed, to be closed
